"""empty message

Revision ID: 42a8d685a735
Revises: db22a3f0ce7b
Create Date: 2025-03-14 13:48:21.931738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a8d685a735'
down_revision = 'db22a3f0ce7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('tag_value', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
